# Hardware Configuration
hardware:
  camera:
    device_id: 0
    resolution:
      width: 640
      height: 480
  motor:
    # GPIO22
    dir_pin: 15   
    # GPIO23
    step_pin: 16  
    # GPIO24
    en_pin: 18

# Vision Configuration
vision:
  image_size: [224, 224]
  confidence_threshold: 0.7
  # Number of consecutive changes needed to switch states
  required_consecutive_changes: 2  
  # Number of frames to average for each prediction
  frame_buffer_size: 3

# AWS Configuration
aws:
  region: us-east-1
  thing_name: SnackBotCore
  thing_group: SnackBotGroup