# Hardware Configuration
vision:
  image_size: [224, 224]
  confidence_threshold: 0.7

hardware:
  camera:
    device_id: 0
    resolution:
      width: 640
      height: 480
  motor:
    step_pin: 16
    dir_pin: 15
    en_pin: 18

# AWS Configuration
aws:
  region: us-east-1
  thing_name: EdgeSnackDispenserThing
  thing_group: EdgeSnackDispenserThingGroup